version: "3.7"
services:
  scrapper:
    image: scrapper
    build:
      context: .
    networks:
      - scrappernet
    ports:
      - "9010:80"
    environment:
      - SERVER_DEPLOYMENT_TYPE=deployment
    cap_drop:
      - ALL
    entrypoint: ["/docker-entrypoint.sh"]
networks:
  scrappernet:
